#!/usr/bin/python2

#
# term-war
#
# Copyright (c) 2013
#
# Author Branislav Blaskovic <branislav@blaskovic.sk>
#

import sys
from connection import ServerConnection
from game import MainGame

# Wanna usage?
if len(sys.argv) < 3:
    print "Usage: " + sys.argv[0] + " host port"
    sys.exit(1)

game = MainGame()

con = ServerConnection(sys.argv[1], int(sys.argv[2]), game)
